[[redirects]]
  from = "/feed"
  to = "/feed/index.xml"
  status = 200
  force = true

[[redirects]]
  from = "/es/feed"
  to = "/es/feed/index.xml"
  status = 200
  force = true


[[redirects]]
  from = "/comments/feed"
  to = "/comments/feed/index.xml"
  status = 200
  force = true


[[redirects]]
  from = "/es/comments/feed"
  to = "/es/comments/feed/index.xml"
  status = 200
  force = true
